language: php

sudo: false

php:
    - 5.6
    - 7.0

install:
    - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > ~/.composer/auth.json
    - composer install --prefer-dist


script:
    - php magento-coding-standard/vendor/bin/phpcs --standard=vendor/eadesignro/module-pdfgenerator/Test/Php/_files/phpcs/ruleset.xml vendor/eadesignro/module-pdfgenerator/
    - php vendor/bin/phpmd vendor/eadesignro/module-pdfgenerator/ text vendor/eadesignro/module-pdfgenerator/Test/Php/_files/phpmd/ruleset.xml
    - php vendor/bin/phpunit Test/

env:
    global:
        - secure: "FgGpwhlejc1sg5h7H5gv3gZmcy4s4YLyLZXUelz3zqg38lt5+6HGciBZo0WZNJAqzaueluuR7Z1twoA0pRu2oupR4y/9aI5S7UThdGpb3dUS7rjoGCvBmWjwXGw2HnY3WMbYo5nqXdrQQtuOrNCar0O/mPsa+v1XP49kap4PxeKklROJVKZOF5Ln6ukrYRXmJ/G3TPupLhT48Z4DkjpBXxHcXM8K2rww62VBX2PMOayajLuUjV1wuIDK+N4nADXRetFxoUbFjoENqzJC36TkYUBqwHL7o9ILCS6NU1EEDBBFi5QCraflPcmHlI2ShDnWSvmUHI92xJHVxnR1WiGhoX2/0Hy776tezUCVGRrTgngA/GW5aPeLFTfwUZ/6RkK0YJ3g3lCAImfrdvYWdJbFko69mirBYQYxgDDErhIbi3mVjJw4GBY3UVD17PRT3LytEyMjObwRHTI8InX7RqWKGVCiVcnQOvhzxo+k6INvz4nugRyPoDQexGYz3N2L1F1V1PgEau4TnbGB40RGKblRCFMhWLiRsWc++l57ZQii6X2gmiGYIuG5SHKbgyHTze63DCuDr4MYZPZBdup8O7tZv8ZS+0MXjWjIgWipVQrz92m08Pqb8HJuG5mqQEBpVc03zyCfzfW5/g3kgDCcAWF5qwF29br9hZmip3YsVtU3/T8="
        - secure: "LLG/A9Q1v2tOs+jv0ZUT6EOBvCuT/fZ6NTwMkAz0gK22GBSSg4vRKD7fy8UC1cra2/0v/wyI7zLN4tur5WKiuN7pGyFzD0pmdnJz7CjACQWJx+IXWJ/hLKFeamnaoq4N3WkoMrlH9cBzJEsFWIkkUUA8AzrOdT6MoMIcudU60tnI66GczrqNBYC/fRJ+sfpd9A1wXC8gFC2J1hOu2CKKTCHO6hFwByF0O8u04op8jBZ9gTQ+ozxScvyKpjge205v96B/G4Nc9elTQWILUfrLiiIzl0N259yUlQAT1aLMnq1deyj/x2OQnjuNob+WSNpVCLVrXSharRgEQATsXMNdPf4LF8d8W5V7msOar34dXoSd7OoNiTS42tw5mKbaeFBQxxZXClsAXxtgFi1DmUoVEOL//gvGyaicHdK4zM1m2zZ0h02QfCy7bO+4BhMzl8fRlgLtpqatGfd6e7i7jpP1x3stFn4LZK/y3Z2ilzuf5/y7cpUlUNJPcpznSR4pL87vyqVBM8q4zrWIKtpM6C/j99wJzi+DcBmlOk5bsBFNIaIFzuzJFzztCB40cKcCuGnFxs6u6DdYo4etrYG240QN+q1uVktRnUP3CD89iulvraLf3Ww4odGCnBuLkhRwXvVyswLnEyMAZDoWfyXYJ6qZ57kBbMphRKx5TbPOmGN9MVI="
